### ISSUE TITLE
Browser's internal pages not opened by URL schemes

### ISSUE THREAD

**Issue by Ricky-Tigg** [duckduckgo/privacy-test-pages#188]
v.: 0.67.0.  Hello. URL schemes are expected to open web browser's internal pages. This browser has no internal pages to open. Tested:  `about:`, `ddgLaunch:`, `ddgQuickLink:`, `zoomus:`, `custom:`, `intent:`, `shortcuts:`.

**Comment by brindy** [comment]
Hi @Ricky-Tigg, can you please direct your feedback to the appropriate browser project:

* https://github.com/DuckDuckGo/Android
* https://github.com/DuckDuckGo/iOS

Thanks!
