### ISSUE TITLE
Aw, Snap! crash in canary

### ISSUE THREAD

**Issue by abrahamjuliot** [duckduckgo/privacy-test-pages#40]
https://privacy-test-pages.glitch.me/privacy-protections/fingerprinting/

The test is crashing in canary 92.0.4512.3 (tested on Win64). It appears `MediaSource.isTypeSupported('audio/mpeg;codecs="mp3"')` mimeType is causing this.

**Comment by kdzwinel** [comment]
Thanks a lot, I opened a Chromium issue here: http://crbug.com/1211290 . Ideally browsers shouldn't crash, even if page is doing something crazy :)

**Comment by kdzwinel** [comment]
I can no longer repro this in Chrome 96 (canary).
